name: AuditKeyValues
visualization:
  options:
    columns: '[{"type":"field","fieldName":"@timestamp","width":210},{"type":"field","fieldName":"@rawstring"}]'
    newestAtBottom: 'true'
    showOnlyFirstLine: 'false'
  type: list-view
$schema: https://schemas.humio.com/query/v0.1.0
timeInterval:
  isLive: false
  start: 1y
queryString: |-
  writeJson(AuditKeyValues, as=_json)
  | replace(field=_json, as=_json, regex="(^\\{\"AuditKeyValues\":\\[)|(\\]\\}$)|(\\\"Key\\\":)|(,\\\"ValueString\\\")", with="")
  | replace(field=_json, as=_json, regex="\\},\\{", with=",")
  | parseJson(_json) | drop([_json])
